In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array; 다차원배열)

In [2]:
# 리스트를 다차원배열로 변환
# array() : 다차원배열을 만드는 함수
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [3]:
li_arr

array([1, 2, 3, 4])

In [4]:
type(li_arr)

numpy.ndarray

In [5]:
# 튜플을 다차원배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [6]:
tu_arr

array([1, 2, 3, 4])

In [7]:
type(tu_arr)

numpy.ndarray

In [8]:
# 배열도 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = li_arr
id(co_arr), id(li_arr)

(2014512161168, 2014512161168)

In [9]:
co_arr[0] = 100
co_arr

array([100,   2,   3,   4])

In [10]:
li_arr

array([100,   2,   3,   4])

In [11]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열을 만들기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [12]:
id(new_arr), id(li_arr)

(2014517232816, 2014512161168)

In [13]:
new_arr[0] = 99
new_arr

array([99,  2,  3,  4])

In [14]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [15]:
# float 자료형을 지정해서 다차원 배열 만들기
fl_arr = np.array(li, dtype = float)
fl_arr

array([1., 2., 3., 4.])

In [16]:
fl_arr.dtype

dtype('float64')

## 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개 이상의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [19]:
# 축의 개수
arr2d.ndim

2

In [20]:
arr2d.dtype

dtype('int32')

In [21]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## 원소 조회하기

In [22]:
# 1차원 배열에서 원소 조회
li_arr

array([100,   2,   3,   4])

In [23]:
li

[1, 2, 3, 4]

In [24]:
li_arr[0]

100

In [25]:
li[0]

1

In [26]:
# 다차원 배열에서 원소 조회
list2d = arr2d.tolist() # 배열을 리스트로 변환

In [27]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [28]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두 번 사용해야함
list2d[0][1]

2

In [31]:
list2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [32]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [34]:
arr2d[0][1]

2

### 슬라이싱

In [35]:
arr1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [37]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [38]:
# 두 번째 행의 두 번째 열부터 끝열까지
arr1[1, 1:]

array([5, 6, 7])

In [39]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

#### 연습문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행렬에서 값 14를 인덱싱
3. 아래의 행렬에서 배열 [6, 7]을 슬라이싱
4. 아래의 행렬에서 배열 [7, 12]를 슬라이싱
5. 아래의 행렬에서 배열 [[3, 4], [8, 9]]를 슬라이싱

In [40]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [41]:
# 7 인덱싱
m[1, 2]

7

In [43]:
# 14 인덱싱
m[-1, -1]

14

In [44]:
# [6, 7] 슬라이싱
m[1, 1:3]

array([6, 7])

In [45]:
# [7, 12] 슬라이싱
m[1:, 2]

array([ 7, 12])

In [46]:
# [[3, 4], [8, 9]] 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [47]:
m = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [22, 23, 24]]])

1. [8, 14] 슬라이싱
2. [[11, 12], [17, 18]] 슬라이싱
3. [3, 9, 15, 21] 슬라이싱

In [48]:
# [8, 14] 슬라이싱
m[1:3, 0, 1]

array([ 8, 14])

In [49]:
# [[11, 12], [17, 18]]
m[1:3, 1, 1:]

array([[11, 12],
       [17, 18]])

In [50]:
# [3, 9, 15, 21]
m[:, 0, 2]

array([ 3,  9, 15, 21])

## 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 곱셈으로 리스트 요소를 반복하는 것은 가능
    
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr.shape

(2, 3)

In [53]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
arr.T.shape

(3, 2)

# 배열 크기 변형

In [2]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr1.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [5]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [8]:
arr1.reshape(-1, 5)

ValueError: cannot reshape array of size 12 into shape (5)

# 넘파이 함수의 특징

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
    
- 유니버설 함수(universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [9]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [10]:
type(test)

function

In [11]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [12]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

function

In [14]:
list2d = [[1, 2, 3], [4, 5, 6]]

In [15]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [16]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

### 벡터화 연산이 필요한 이유

- data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [17]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
ans = []

for i in data:
    ans.append(i * 2)
    
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [20]:
# 넘파이를 통한 풀이
data = np.array(data)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [22]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [23]:
2 * a + b

array([12, 24, 36])

In [24]:
a == 2

array([False,  True, False])

In [25]:
[1, 2, 3] == 2

False

In [26]:
b > 10

array([False,  True,  True])

In [27]:
(a == 2) & (b > 10)

array([False,  True, False])

In [30]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [31]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [32]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [33]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [34]:
# arr1에 차원 추가(수직축 추가)
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [35]:
new_arr1.shape

(4, 1)

In [36]:
# arr2에 차원 추가(수평축 추가)
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [37]:
new_arr2.shape

(1, 4)

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤

In [38]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

In [39]:
# 행렬곱 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [40]:
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
b

array([[5, 6],
       [7, 8]])

In [44]:
# * 연산자는 요소별 곱셈을 수행
a * b

array([[ 5, 12],
       [21, 32]])

In [45]:
# @ 연산자는 행렬 곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

#### 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수 찾기
3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기

In [46]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [51]:
x[2::3]

array([ 3,  6,  9, 12, 15, 18])

In [54]:
# 4로 나누면 1이 남는 수 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [56]:
# 3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요

In [57]:
# 1차원배열
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [58]:
# 합계
np.sum(arr1)

10

In [59]:
arr1.sum()

10

In [60]:
# 최댓값
arr1.max()

4

In [61]:
# 최솟값
arr1.min()

1

In [62]:
# 최솟값의 위치
arr1.argmin()

0

In [63]:
# 최댓값의 위치
arr1.argmax()

3

In [64]:
# 평균
arr1.mean()

2.5

In [65]:
# 중앙값
np.median(arr1)

2.5

In [67]:
# 2차원 배열
arr2 = arr1.reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [68]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [69]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [70]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [71]:
# 3차원 배열
arr3 = np.arange(1, 9)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
arr4 = arr3.reshape(2, 2, 2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [73]:
# 모든 원소를 더한 합
np.sum(arr4)

36

In [74]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr4, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [75]:
# 각 2차원 배열의 0번축(열)의 합
np.sum(arr4, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [76]:
# 각 2차원 배열의 1번축(행)의 합
np.sum(arr4, axis = 2)

array([[ 3,  7],
       [11, 15]])

#### 연습문제

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [77]:
x = np.random.random((5, 6))
x

array([[0.0095874 , 0.95508437, 0.12430655, 0.47186223, 0.71925721,
        0.30437823],
       [0.89480351, 0.02735902, 0.85637029, 0.47977648, 0.29233283,
        0.90764022],
       [0.93154398, 0.7378313 , 0.69945863, 0.69884473, 0.2529206 ,
        0.79507437],
       [0.33636752, 0.08148859, 0.50263465, 0.16080013, 0.13795516,
        0.26704294],
       [0.46212646, 0.50173493, 0.3118937 , 0.92029944, 0.54838744,
        0.78340246]])

In [78]:
x.shape

(5, 6)

In [79]:
# 전체의 최댓값
x.max()

0.955084374293177

In [80]:
# 각 행의 합
x.sum(axis = 1)

array([2.58447599, 3.45828234, 4.1156736 , 1.48628899, 3.52784443])

In [81]:
# 각 행의 최댓값
x.max(axis = 1)

array([0.95508437, 0.90764022, 0.93154398, 0.50263465, 0.92029944])

In [82]:
# 각 열의 평균
x.mean(axis = 0)

array([0.52688577, 0.46069964, 0.49893276, 0.5463166 , 0.39017065,
       0.61150764])

In [83]:
# 각 열의 최솟값
x.min(axis = 0)

array([0.0095874 , 0.02735902, 0.12430655, 0.16080013, 0.13795516,
       0.26704294])

In [84]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [85]:
arr4.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [86]:
arr4.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [87]:
arr4.sum(axis = 2)

array([[ 3,  7],
       [11, 15]])

In [88]:
arr4.sum(axis = (0, 1))

array([16, 20])

In [89]:
arr4.sum(axis = (0, 2))

array([14, 22])

In [90]:
arr4.sum(axis = (1, 2))

array([10, 26])

In [91]:
arr5 = np.random.randint(0, 3, (2, 3, 4))
arr5

array([[[0, 2, 2, 1],
        [1, 1, 0, 1],
        [0, 1, 1, 1]],

       [[1, 0, 1, 1],
        [1, 1, 1, 1],
        [1, 2, 0, 2]]])

In [92]:
arr5.sum(axis = 0)

array([[1, 2, 3, 2],
       [2, 2, 1, 2],
       [1, 3, 1, 3]])

In [93]:
arr5.sum(axis = 1)

array([[1, 4, 3, 3],
       [3, 3, 2, 4]])

In [94]:
arr5.mean(axis = 2)

array([[1.25, 0.75, 0.75],
       [0.75, 1.  , 1.25]])

In [95]:
arr5.mean(axis = (0, 1))

array([0.66666667, 1.16666667, 0.83333333, 1.16666667])

In [96]:
arr5.mean(axis = (0, 2))

array([1.   , 0.875, 1.   ])

In [97]:
arr5.mean(axis = (1, 2))

array([0.91666667, 1.        ])

In [99]:
data_3d = np.random.random((3, 5, 6))

1. 각 2차원 배열에서의 최댓값
2. 각 2차원 배열에서의 행의 합
3. 각 2차원 배열에서의 각 행의 최댓값
4. 전체 열의 평균
5. 각 2차원 배열에서의 열의 평균
6. 각 2차원 배열에서의 각 열의 최솟값

In [102]:
# 각 2차원 배열에서의 최댓값
data_3d.max(axis = (1, 2))

array([0.91456409, 0.97601941, 0.97989033])

In [101]:
# 각 2차원 배열에서의 행의 합
data_3d.sum(axis = 2)

array([[4.08528247, 3.88868876, 2.85629104, 2.22753187, 2.51838731],
       [2.74615653, 4.00388406, 3.99098739, 2.91280452, 3.21767673],
       [3.67421302, 3.80324837, 2.83622132, 2.60471525, 2.6697419 ]])

In [103]:
# 각 2차원 배열에서의 각 행의 최댓값
data_3d.max(axis = 2)

array([[0.89061359, 0.82853182, 0.85521152, 0.91456409, 0.72850428],
       [0.92781128, 0.93334354, 0.97601941, 0.95331513, 0.88411028],
       [0.9277787 , 0.94122807, 0.97989033, 0.95965887, 0.84056644]])

In [104]:
# 전체 열의 평균
data_3d.mean(axis = (0, 1))

array([0.49086413, 0.64956087, 0.63012263, 0.42826796, 0.61954508,
       0.38402803])

In [105]:
# 각 2차원 배열에서의 열의 평균
data_3d.mean(axis = 1)

array([[0.60322067, 0.59313885, 0.59752204, 0.29221666, 0.59684935,
        0.43228871],
       [0.39821888, 0.60385129, 0.63075504, 0.62581106, 0.55209733,
        0.56356825],
       [0.47115285, 0.75169246, 0.6620908 , 0.36677617, 0.70968854,
        0.15622714]])

In [106]:
# 각 2차원 배열에서의 각 열의 최솟값
data_3d.min(axis = 1)

array([[0.03191569, 0.3618083 , 0.2527471 , 0.05446732, 0.17754012,
        0.14503695],
       [0.15413032, 0.19716806, 0.41472234, 0.18795177, 0.17606277,
        0.27621244],
       [0.07290358, 0.38668517, 0.28859403, 0.12670951, 0.42239582,
        0.00994143]])

# Inf 와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음

In [108]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\ITSC\AppData\Local\Temp\ipykernel_5960\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\ITSC\AppData\Local\Temp\ipykernel_5960\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])