In [26]:
from tensorflow import keras
import pandas as pd 
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')


In [3]:
data = datasets.load_iris()

In [4]:
# bunch 타입
type(data)

sklearn.utils._bunch.Bunch

- 여러가지 데이터 type 에 대해서 다룰 수 있어야 함
- Data_Scientist는 데이터를 자유롭게 다룰 수 있어야 함

In [6]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
df['species'] = data.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [11]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

- 강사님 제자들이 빵점맞은 문제

### 데이터엔 문자열이 들어가면 안됨

In [10]:
df['species'].map({0: 'setosa', 1 : 'versicolor', 2 : 'virginica'})

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [12]:
df.shape

(150, 5)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


- 150개행의 4개의 독립변수
- 4개 전부 수치형 
- 결측치 없음

In [14]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

- 평균값 조금 차이 나고, 표준편차도 차이가 아예 안나는 것은 아님
- 모든 것들이 신경거슬릴만큼만 차이가 나서 
- 스케일링 하는 것이 나을 수 있겠다.

이번챕터에서는 스케일링 건너뛸것임

In [16]:
# 0~2번까지 전부 50개씩 만들어져 있는 예쁜 데이터 
np.unique(df['species'], return_counts = True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [18]:
# 위에와 같음 
y.value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

## 데이터 분할

In [17]:
x = df.drop('species', axis = 1)
y = df['species']

In [19]:
# 딥러닝 모델은 처음부터 끝까지 논리를 세워야 함 
# 여기서 어떤 층이 들어왔고 목적이 무엇이었는지 명확해야 함 
x.shape

(150, 4)

- x 데이터가 150컬럼과 4의 shape를 가지고 있음

In [20]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [21]:
# 몇차원인지 모르겠으면 iloc뽑아보기 
# 시리즈는 1차원 
# 4개의 데이터가 1차원으로 들어와 있음 
x.iloc[0]

sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

In [22]:
# 모델 구성

model = keras.Sequential()

# 입력층과 맞닿아 있는 층 : 입력값에 모양새가 어떻게 되는지 잘 적어야 함 
# Dense(16 -> 은닉층의 유닛수만 자유, 아무렇게나 해도 됨 
# input_shape = (4, ) -> 입력층은 자유x 
model.add(keras.layers.Dense(16, activation = 'relu', input_shape = (4, )))

# 이제 분류 (유닛숫자 당 3개가 필요함) 정해짐 
# 출력층은 형태가 정해져 있음 
model.add(keras.layers.Dense(3, activation = 'softmax'))

C:\Users\ITSC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
y.shape

(150,)

In [25]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', 
              metrics = ['accuracy'])

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify = y, test_size = 0.2, 
                                                    random_state= 12)

In [29]:
x_sub, x_val, y_sub, y_val = train_test_split(x_train, y_train, stratify = y_train,
                                              test_size = 0.2, random_state = 12)

In [31]:
# batch_size 한줄 꺼내서 가중치 돌리고 한줄 꺼내서 가중치 돌리고 : 확률 경사법 
# 딥러닝은 기본적으로 미니 배치사이즈를 쓺 
# 배치사이즈 기본값 32
model.fit(x_sub, y_sub, epochs = 50, validation_data = (x_val, y_val), batch_size = 4)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5012 - loss: 0.9153 - val_accuracy: 0.5417 - val_loss: 0.9002
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5364 - loss: 0.9046 - val_accuracy: 0.5833 - val_loss: 0.8661
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5019 - loss: 0.8598 - val_accuracy: 0.5417 - val_loss: 0.8322
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6387 - loss: 0.8140 - val_accuracy: 0.5417 - val_loss: 0.8020
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4942 - loss: 0.8173 - val_accuracy: 0.6250 - val_loss: 0.7749
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6158 - loss: 0.7855 - val_accuracy: 0.6250 - val_loss: 0.7500
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7004 - loss: 0.7336 - val_accuracy: 0.6667 - val_loss: 0.7278
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7004 - loss: 0.7001 - val_accuracy: 0.6667 - val_loss:

- to_categorical()

In [32]:
# 데이터를 가공하기
# 종속변수를 sparse를 하게 만드는 게 정석
encoded_y = keras.utils.to_categorical(y)

In [33]:
encoded_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, encoded_y, stratify = encoded_y, 
                                                    test_size = 0.2, random_state = 12)

In [35]:
x_sub, x_val, y_sub, y_val = train_test_split(x_train, y_train, stratify = y_train,
                                              test_size = 0.2, random_state = 12)

In [36]:
y_val[:5]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [37]:
model2 = keras.Sequential()
model2.add(keras.layers.Dense(16, activation = 'relu', input_shape = (4, )))
model2.add(keras.layers.Dense(3, activation = 'softmax'))

In [38]:
model2.compile(loss = 'categorical_crossentropy',
               optimizer = 'adam', metrics = ['accuracy'])

In [39]:
# batch_size 는 맘대로 해도 됨 
model2.fit(x_sub, y_sub, epochs = 100, batch_size = 8, validation_data= (x_val, y_val))

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5730 - loss: 1.2789 - val_accuracy: 0.5000 - val_loss: 1.1645
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4893 - loss: 1.1474 - val_accuracy: 0.6250 - val_loss: 1.0974
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5371 - loss: 1.1490 - val_accuracy: 0.6250 - val_loss: 1.0519
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5503 - loss: 1.1018 - val_accuracy: 0.6250 - val_loss: 1.0273
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5801 - loss: 1.0585 - val_accuracy: 0.7083 - val_loss: 1.0104
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6804 - loss: 1.0137 - val_accuracy: 0.7083 - val_loss: 0.9928
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7060 - loss: 1.0112 - val_accuracy: 0.7500 - val_loss: 0.9762
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7729 - loss: 0.9846 - val_accuracy: 0.7500 - 

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8652 - loss: 0.4970 - val_accuracy: 0.8750 - val_loss: 0.4875
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9017 - loss: 0.4803 - val_accuracy: 0.8750 - val_loss: 0.4789
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9110 - loss: 0.4537 - val_accuracy: 0.8750 - val_loss: 0.4708
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8994 - loss: 0.4559 - val_accuracy: 0.8750 - val_loss: 0.4642
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9347 - loss: 0.4279 - val_accuracy: 0.8750 - val_loss: 0.4600
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8995 - loss: 0.4833 - val_accuracy: 0.8750 - val_loss: 0.4540
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8694 - loss: 0.4577 - val_accuracy: 0.8750 - val_loss: 0.4488
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9242 - loss: 0.4198 - val_accuracy: 0.8750 - val_lo

batch_size를 설정하지 않으면 기본값 32
따라서 input_shape 나 outpu_shape의 첫 번째 차원을 배치 차원이라고도 부름