In [40]:
import sys
print(sys.version)

3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]


# 양방향 LSTM

- RNN 이나 LSTM은 시퀀스 또는 시계열 데이터 처리에 특화되어 은닉층에서 과거의 정보를 기억할 수 있음
- 그러나 순환 구조의 특성상 데이터가 입력 순으로 처리되기 때문에 이전 시점의 정보만 활용할 수 밖에 없다는 단점이 존재 
    - 문장이 길어질수록 성능이 저하 
    - 예) ios 앱 (개발)은 맥북이 필요 합니다 
    - 위의 경우에 ios와 앱 이라는 단어만으로는 개발 이라는 단어를 유추하기 힘듦
        - 문장의 앞부분보다 뒷부분에 중요한 정보가 있음 
        
- 양방향 LSTM(Bidirectional LSTM)
    - 기존 LSTM 계층에 역방향으로 처리하는 LSTM 계층을 추가해 양방향에서 문장의 패턴을 분석할 수 있도록 구성 
    - 입력 문장을 양방향에서 처리하기 때문에 시퀀스 길이가 길어져도 정보 손실 없이 처리가 가능 
    
<img src = './image/Bidirectional_LSTM.jpg'>

# 개체명 인식(Named Entitiy Recognition)

- 각 개체의 유형을 인식 
- 문장 내에 포함된 어떤 단어가 인물, 장소, 날짜 등을 의미한느 단어인지 인식하는 것 
- 개체명 인식은 챗봇에서 문장을 정확하게 해석하기 위해 반드시 처리해야 하는 전처리 과정임 
    - 예) 날짜와 지역에 대해 개체 인식을 할 수 있는 모델이 있다고 가정할 경우 
    - 입력 문장 : 내일 부산 날씨 알려줘
    - 문장 의도 : 날씨 요청
    - 개체명 인식 결과 : 내일 - 날짜, 부산, - 지역 
    
- 단순한 질문 형태라면 개체명 사전을 구축해 해당 단어들과 매핑되는 개체명을  찾을 수도 있음 
    - 문장 구조가 복잡하거나 문맥에 따라 단어의 의미가 바뀐다면 딘러닝 모델을 활용해야 함 
    
- 개체명 사전 구축 방식은 신조어나 사전에 포함되지 않은 단어는 처리 불가능하며 사람이 직접 사전 데이터를 관리해야 하기 때문에 관리비용이 많이 필요함 

## BIO 표기법 

- Beginning, Inside, Outside 의 약자 
- 각 토큰마다 태그를 붙이기 위해 사용 
- Beginning : 개체명이 시작되는 단어에 'B-개체명' 으로 태그
- Inside : 'B-개체명'과 연결되는 단어일 때 'I-개체명'으로 태그 
- Outside : 개ㅔ체명 이외의 모든 토큰에 태그 
    - 예) 오늘부터 길동 포터는 삼정전자에 근무합니다
    - 오늘 -> B-date 
    - 부터 -> O
    - 길동 -> B-Person
    - 포터 -> I-Person
    - 는 -> O
    - 삼성 -> B-Company
    - 전자 -> I-Company
    - 에 -> O
    - 근무 -> O
    - 합니다 -> O
    
- 두개 이상의 토큰이 하나의 개체를 구성하는 경우가 많기 때문에 BIO 표기법을 사용 

## 국립국어원 언어정보나눔터 개체명 인식 모델을 위한 말뭉치

- ; 으로 시작하는 문장 : 원본 문장 
- $ 로 시작하는 문장 : 해당 문장에서 NER 처리된 결과
- 개체명 인식 모델은 단어 토큰을 입력했을 때 출력되는 NER 태그값을 예측
    - 예) "삼성전자"를 입력한담녀 B_OG(단체) 태그가 출력 되도록 학습 

In [2]:
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import preprocessing 
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (LSTM, Embedding, Dense, TimeDistributed, Dropout,
                                     Bidirectional)
from tensorflow.keras.optimizers import Adam
from seqeval.metrics import f1_score, classification_report 

In [3]:
# 학습 파일 불러오기
def read_file(file_name):
    sents = []
    with open(file_name, 'r', encoding = 'utf-8') as f: # r for read 
        lines = f.readlines() # 읽어와서 list로 불러들임 
        for idx, L in enumerate(lines):
            # 라인의 0번째 세미콜론이고 그다음이 $ 이면 
            # this_sent 를 초기화 
            if L[0] == ';' and lines[idx + 1][0] == '$':
                this_sent = []
                
            # 달러로 시작하면  그대로 넘어가라 
            elif L[0] == '$' and lines [idx - 1][0] == ';':
                continue
                
            # 엔터 들어가면 이문장에 대한 내용이 끝난걸로 인식해라 
            elif L[0] == '\n':
                sents.append(this_sent) # 리스트에 append 해라 
            else:
                this_sent.append(tuple(L.split()))
    return sents   

In [5]:
# 학습용 말뭉치 데이터를 불러옴
corpus = read_file('./data/ner/train.txt')

In [7]:
corpus[1]

[('1', '2003', 'SN', 'B_DT'),
 ('1', '년', 'NNB', 'I'),
 ('2', '6', 'SN', 'I'),
 ('2', '월', 'NNB', 'I'),
 ('3', '14', 'SN', 'I'),
 ('3', '일', 'NNB', 'I'),
 ('4', '사직', 'NNG', 'O'),
 ('5', '두산', 'NNP', 'O'),
 ('5', '전', 'NNG', 'O'),
 ('6', '이후', 'NNG', 'O'),
 ('7', '박명환', 'NNP', 'B_PS'),
 ('7', '에게', 'JKB', 'O'),
 ('8', '당하', 'VV', 'O'),
 ('8', '았', 'EP', 'O'),
 ('8', '던', 'ETM', 'O'),
 ('9', '10', 'SN', 'O'),
 ('9', '연패', 'NNG', 'O'),
 ('10', '사슬', 'NNG', 'O'),
 ('10', '을', 'JKO', 'O'),
 ('11', '거의', 'MAG', 'O'),
 ('12', '5', 'SN', 'B_DT'),
 ('12', '년', 'NNB', 'I'),
 ('13', '만', 'NNB', 'O'),
 ('13', '에', 'JKB', 'O'),
 ('14', '끊', 'VV', 'O'),
 ('14', '는', 'ETM', 'O'),
 ('15', '의미', 'NNG', 'O'),
 ('15', '있', 'VV', 'O'),
 ('15', '는', 'ETM', 'O'),
 ('16', '승리', 'NNG', 'O'),
 ('16', '이', 'VCP', 'O'),
 ('16', '었', 'EP', 'O'),
 ('16', '다', 'EC', 'O'),
 ('17', '.', 'SF', 'O')]

In [8]:
len(corpus)

3555

In [9]:
# 말뭉치 데이터에서 단어와 BIO 태그만 불러와 학습용 데이터셋 생성
# corpus 에서 반복문 
sentences, tags = [], []

for t in corpus:
    tagged_sentence = []
    sentence, bio_tag = [], []
    for w in t:
        tagged_sentence.append((w[1], w[3]))
        sentence.append(w[1])
        bio_tag.append(w[3])
        
    sentences.append(sentence)
    tags.append(bio_tag)

- 단어와 BIO 태그만 이용해 학습용 데이터셋을 생성 

In [10]:
print('샘플 크기 :', len(sentences))
print('0번째 샘플 문장 시퀀스: \n', sentences[0])
print('0번째 샘플 bio 태그 : \n', tags[0])
print('샘플 문장 시퀀스 최대 길이:', max(len(L) for L in sentences))
print('샘플 문장 시퀀스 평균 길이 :', sum(map(len, sentences)) / len(sentences))

샘플 크기 : 3555
0번째 샘플 문장 시퀀스: 
 ['한편', ',', 'AFC', '챔피언스', '리그', 'E', '조', '에', '속하', 'ㄴ', '포항', '역시', '대회', '8강', '진출', '이', '불투명', '하', '다', '.']
0번째 샘플 bio 태그 : 
 ['O', 'O', 'O', 'O', 'O', 'B_OG', 'I', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
샘플 문장 시퀀스 최대 길이: 168
샘플 문장 시퀀스 평균 길이 : 34.03909985935302


In [11]:
# 토크나이저 정의

# 단어 사전의 첫번째 인덱스에는 OOV 사용 
sent_tokenizer = preprocessing.text.Tokenizer(oov_token = 'OOV') 
sent_tokenizer.fit_on_texts(sentences)

tag_tokenizer = preprocessing.text.Tokenizer(lower = False) # 태그 정보는 소문자로 변환하지 않음 
tag_tokenizer.fit_on_texts(tags)

In [12]:
# 단어 사전 및 태그 사전 크기 
vocab_size = len(sent_tokenizer.word_index) + 1
tag_size = len(tag_tokenizer.word_index) + 1
print('BIO 태그 사전 크기 :', tag_size)
print('단어 사전 크기 :', vocab_size)

BIO 태그 사전 크기 : 8
단어 사전 크기 : 13834


In [13]:
tag_tokenizer.word_index

{'O': 1, 'I': 2, 'B_OG': 3, 'B_PS': 4, 'B_DT': 5, 'B_LC': 6, 'B_TI': 7}

In [14]:
# 학습용 단어 시퀀스 생성
x_train = sent_tokenizer.texts_to_sequences(sentences)
y_train = tag_tokenizer.texts_to_sequences(tags)

In [15]:
print(x_train[0])
print(y_train[0])

[183, 11, 4276, 884, 162, 931, 402, 10, 2608, 7, 1516, 608, 145, 1361, 414, 4, 6347, 2, 8, 3]
[1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [16]:
# index to word / index to NER 정의 
index_to_word = sent_tokenizer.index_word # 시퀀스 인덱스를 단어로 변환하기 위해 사용
index_to_ner = tag_tokenizer.index_word # 시퀀스 인덱스를 NER로 변환하기 위해 사용
index_to_ner[0] = 'PAD'

In [17]:
index_to_ner

{1: 'O',
 2: 'I',
 3: 'B_OG',
 4: 'B_PS',
 5: 'B_DT',
 6: 'B_LC',
 7: 'B_TI',
 0: 'PAD'}

In [18]:
# 시퀀스 패딩 처리
max_len = 40
x_train = preprocessing.sequence.pad_sequences(x_train, padding = 'post', maxlen = max_len)
y_train = preprocessing.sequence.pad_sequences(y_train, padding = 'post', maxlen = max_len)

In [19]:
# 학습데이터와 테스트데이터를 8:2 비율로 분리
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size= 0.2,
                                                    random_state= 12)

In [20]:
# 출력 데이터를 원-핫 인코딩
y_train = tf.keras.utils.to_categorical(y_train, num_classes= tag_size)
y_test = tf.keras.utils.to_categorical(y_test, num_classes= tag_size)

In [21]:
print('학습 샘플 시퀀스 형상 :', x_train.shape)
print('학습 샘플 레이블 형상 :', y_train.shape)
print('테스트 샘플 시퀀스 형상 :', x_test.shape)
print('테스트 샘플 레이블 형상 :', y_test.shape)

학습 샘플 시퀀스 형상 : (2844, 40)
학습 샘플 레이블 형상 : (2844, 40, 8)
테스트 샘플 시퀀스 형상 : (711, 40)
테스트 샘플 레이블 형상 : (711, 40, 8)


In [22]:
x_train[0]

array([ 479,    6,   33,  327, 2615,    9, 2207,    4,   18,   62, 6379,
          5, 6380,    2,    6,  183, 4295,   10,   57,    7, 6381,  186,
        611,   10,   34, 1368,  500,   29,   38,    4,    8,    3,    0,
          0,    0,    0,    0,    0,    0,    0])

In [24]:
# 모델 정의(Bi-LSTM)
model = Sequential()

# output_dim : 출력 벡터의 크기 
model.add(Embedding(input_dim = vocab_size, output_dim = 30, input_shape = (max_len,),
                    mask_zero= True))
model.add(Bidirectional(LSTM(200, return_sequences = True, dropout = 0.5, 
                             recurrent_dropout= 0.25)))
model.add(TimeDistributed(Dense(tag_size, activation = 'softmax')))

C:\Users\ITSC\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:81: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


- mask_zero = True : 0으로 패딩된 값을 마스킹하여 네트워크의 뒤로 전달되지 않게 만듦 
- TimeDistributed : many-to-many 로 동작. 각 타임스텝마다 출력이 있어야 함

<img src = './image/time_distributed.jpg'>

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 40, 30)              │         415,020 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ (None, 40, 400)             │         369,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed (TimeDistributed)   │ (None, 40, 8)               │           3,208 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 787,828 (3.01 MB)

 Trainable params: 787,828 (3.01 MB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile(loss = 'categorical_crossentropy', optimizer = Adam(0.01),
              metrics = ['accuracy'])

In [29]:
model.fit(x_train, y_train, batch_size = 128, epochs = 7)

Epoch 1/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 5s 223ms/step - accuracy: 0.7027 - loss: 0.0587
Epoch 2/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 5s 235ms/step - accuracy: 0.6960 - loss: 0.0504
Epoch 3/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 6s 242ms/step - accuracy: 0.7088 - loss: 0.0458
Epoch 4/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 5s 229ms/step - accuracy: 0.7053 - loss: 0.0402
Epoch 5/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 4s 188ms/step - accuracy: 0.7053 - loss: 0.0378
Epoch 6/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 4s 181ms/step - accuracy: 0.7019 - loss: 0.0348
Epoch 7/7
23/23 ━━━━━━━━━━━━━━━━━━━━ 4s 180ms/step - accuracy: 0.7162 - loss: 0.0337


In [30]:
model.evaluate(x_test,y_test)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6770 - loss: 0.2791


[0.2905934154987335, 0.6663501858711243]

# 정리
- BIO 태그는 실제 의미 있는 태그보다 의미없는 0 태그가 대부분을 차지하고 있기 때문에 실제 성능과 무관하게 높은 점수가 나올 수 있음 
- 따라서 개체명 인식에서는 F1스코어가 주로 이용됨 
- F1 스코어 : 정밀도와 재현율의 조화 평균 

In [57]:
# model.predict(x_test[[0]])

In [56]:
# np.argmax(model.predict(x_test[[1]]), axis = -1)

In [33]:
y_test[[0]]

array([[[0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0

In [58]:
# np.argmax(model.predict(x_test[[3]]), axis = -1)

In [36]:
np.argmax(y_test[[3]], axis = -1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [65]:
# 시퀀스를 NER 태그로 변환
def sequences_to_tag(sequences):  # 예측값을 index_to_ner를 사용하여 태깅 정보로 변경하는 함수.
    result = []
    for sequence in sequences:  # 전체 시퀀스로부터 시퀀스를 하나씩 꺼낸다.
        temp = []
        for pred in sequence:  # 시퀀스로부터 예측값을 하나씩 꺼낸다.
            pred_index = np.argmax(pred)  # 예를 들어 [0, 0, 1, 0 ,0]라면 1의 인덱스인 2를 리턴한다.
            temp.append(index_to_ner[pred_index].replace("PAD", "O"))  # 'PAD'는 'O'로 변경
        result.append(temp)
    return result

In [66]:
x_test.shape

(711, 40)

In [67]:
# 테스트 데이터셋의 NER 예측
y_predicted = model.predict(x_test) # (7111, 40) -> model -> (711, 40, 8)
pred_tags = sequences_to_tag(y_predicted) # 예측된 NER
test_tags = sequences_to_tag(y_test) # 실제 NER

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


In [68]:
y_predicted[0]

array([[1.52789312e-07, 9.99980211e-01, 5.68153200e-06, 2.24245653e-07,
        1.30293247e-05, 4.66310695e-07, 2.44705603e-07, 3.52866785e-08],
       [1.49558247e-07, 9.99971390e-01, 1.80202562e-07, 1.00539147e-07,
        2.63592647e-05, 5.25433848e-07, 1.35604182e-06, 6.44301679e-08],
       [1.00390452e-07, 9.99998093e-01, 7.02780625e-08, 4.67123783e-07,
        5.70374766e-07, 1.20995196e-07, 4.70382673e-07, 9.59735615e-08],
       [2.77037593e-08, 9.99995589e-01, 3.76256025e-07, 1.38723371e-08,
        3.81430937e-06, 3.10499431e-08, 2.48023554e-07, 6.77546330e-09],
       [1.55153515e-07, 9.99678850e-01, 1.23935627e-06, 6.28491023e-07,
        3.18656152e-04, 1.05779456e-07, 2.30635436e-07, 3.52250140e-08],
       [1.43770791e-08, 9.99997973e-01, 1.61242917e-06, 1.80353723e-08,
        3.46893984e-07, 3.25588232e-08, 6.50911991e-09, 2.81508878e-08],
       [1.70026766e-07, 9.99975085e-01, 5.87331851e-06, 2.55147347e-06,
        1.56744045e-05, 2.65014734e-07, 3.78695461e-07, 6.

In [69]:
pred_tags[0]

['O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O']

In [70]:
test_tags[0]

['O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O']

In [71]:
print(classification_report(test_tags, pred_tags))

C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_LC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_TI seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_OG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_DT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_PS seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))


              precision    recall  f1-score   support

           _       0.62      0.59      0.60       683
         _DT       0.90      0.86      0.88       357
         _LC       0.74      0.60      0.66       324
         _OG       0.71      0.55      0.62       464
         _PS       0.75      0.45      0.57       388
         _TI       0.87      0.82      0.84        76

   micro avg       0.73      0.61      0.66      2292
   macro avg       0.76      0.64      0.70      2292
weighted avg       0.73      0.61      0.66      2292



In [72]:
print('F1-score: {:.1%}'.format(f1_score(test_tags, pred_tags)))

F1-score: 66.3%


C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_LC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_TI seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_OG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_DT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
C:\Users\ITSC\anaconda3\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: B_PS seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))


In [77]:
# 새로운 유형의 문장 NER 예측
word_to_index = sent_tokenizer.word_index
new_sentences = '삼성전자 출시 스마트폰 오늘 애플 도전장 내밀다'.split()
new_x = []
for w in new_sentences:
    try:
        new_x.append(word_to_index.get(w, 1))
    except KeyError:
        # 모르는 단어의 경우 OOV
        new_x.append(word_to_index['OOV'])

In [78]:
print('새로운 유형의 시퀀스 :', new_x)
new_padded_seqs = preprocessing.sequence.pad_sequences([new_x], padding = 'post',
                                                       maxlen = max_len)

새로운 유형의 시퀀스 : [531, 307, 1476, 286, 1507, 6766, 1]


In [76]:
# NER 예측 
p = model.predict(np.array([new_padded_seqs[0]]))
p = np.argmax(p, axis = -1) # 에측된 NER 인덱스값 추출
print('{:10} {:5}'.format('단어', '예측된 NER'))
print('-' * 50)

for w, pred in zip(new_sentences, p[0]):
    print('{:10} {:5}'.format(w, index_to_ner[pred]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
단어         예측된 NER
--------------------------------------------------
삼성전자       B_OG 
출시         O    
스마트폰       O    
오늘         B_DT 
애플         B_OG 
도전장        I    
내밀다        I    
